django_riddles1234/django_riddles/django_riddles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('riddles/', include('riddles.urls'), name="riddles"),
    url(r'^$', include('user_register_login.urls')),
    url(r'^user/', include('user_register_login.urls')),
]
# urlpatterns = [
#     url(r'^riddles/', include('riddles.urls'), name="riddles"),
#     url(r'^admin/', admin.site.urls),
# ]

django_riddles1234/django_riddles/riddles/urls.py
from django.conf.urls import url

from . import views

app_name = 'riddles'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<riddle_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<riddle_id>[0-9]+)/answer/$', views.answer, name='answer')
]

django_riddles1234/django_riddles/user_register_login/urls.py
from django.conf.urls import url
from django.urls import path
# import views from local directory.
from . import views

urlpatterns = [
    # Не используйте пустую строку в пути запроса, иначе будут перехвачены все url-адреса запросов со всем значением пути запроса
    # url(r'', views.home_page, name='home_page'),
    # если вы хотите перехватить запрос корневого пути приложения django, просто используйте url-адрес R'^$', чтобы отобразить его.
    # Следующее сопоставление url-адресов будет обрабатывать запрос http://127.0.0.1:8000/ с функцией просмотра home_page.
    url(r'^$', views.home_page, name='home_page'),
    # Обращение к url http://127.0.0.1:8000/user/home/
    url(r'^home/$', views.home_page, name='home_page'),
    #Просмотр пользователем http://localhost:8000/user/do_login вызовет функцию do_login, определенную во views.py.
    url(r'^do_login/$', views.do_login, name='do_login'),
    # Обращение к url http://127.0.0.1:8000/user/login_success/, этот url-адрес будет вызван после успешного входа в систему.
    url(r'^login_success/$', views.login_success, name='login_success'),
    # Обращение к url http://127.0.0.1:8000/user/register/
    url(r'^register/$', views.user_register, name='user_register'),
    # При просмотре пользователем http://localhost:8000/user/do_register, будет вызвана функция do_register, описанная во views.py.
    url(r'^do_register/$', views.do_register, name='do_register'),
    # При обращении к url http://127.0.0.1:8000/user/register_success/, этот url-адрес будет вызван после успешной регистрации в системе.
    url(r'^register_success/$', views.register_success, name='register_success'),
]

django_riddles1234/django_riddles/riddles/models.py
from django.db import models


class Riddle(models.Model):
    riddle_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')



class Option(models.Model):
    riddle = models.ForeignKey(Riddle, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

django_riddles1234/django_riddles/user_register_login/models.py
from django.db import models

# Create your models here.

django_riddles1234/django_riddles/riddles/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.contrib import auth

from .models import Riddle, Option



def index(request):
    return render(request, "index.html", {"latest_riddles": Riddle.objects.order_by('-pub_date')[:5]})


def detail(request, riddle_id):
    return render(request, "answer.html", {"riddle": get_object_or_404(Riddle, pk=riddle_id)})


def answer(request, riddle_id):
    riddle = get_object_or_404(Riddle, pk=riddle_id)
    try:
        option = riddle.option_set.get(pk=request.POST['option'])
    except (KeyError, Option.DoesNotExist):
        return render(request, 'answer.html', {'riddle': riddle, 'error_message': 'Option does not exist'})
    else:
        if option.correct:
            return render(request, "index.html", {"latest_riddles": Riddle.objects.order_by('-pub_date')[:5], "message": "Смелее! Выберите какую-нибудь загадку!"})
        else:
            return render(request, 'answer.html', {'riddle': riddle, 'error_message': 'Ответ неверный! Попробуйте еще раз.'})

django_riddles1234/django_riddles/user_register_login/views.py
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from rest_framework.generics import RetrieveUpdateAPIView

from rest_framework_jwt.utils import jwt_payload_handler, jwt_encode_handler

from django.contrib.auth.models import User
from django.contrib.auth import authenticate


@permission_classes([AllowAny, ])
def home_page(request):
    return render(request, 'user_login.html')

def do_login(request):

    request_method = request.method

    print('request_method = ' + request_method)

    if request_method == 'POST':
        user_name = request.POST.get('user_name','')
        user_password = request.POST.get('user_password', '')

        user = authenticate(username=user_name, password=user_password)

        if  user is not None:

            payload = jwt_payload_handler(user)
            token = jwt_encode_handler(payload)
            
            user_details = {}
            user_details['username'] = user_name
            user_details['token'] = token

            # Перенаправление страницы на страницу login_success.
            response = HttpResponseRedirect('/user/login_success/')
            print('===================== response')
            print(response)
            # Установка cookie для передачи имени пользователя на страницу login_success.
            response.set_cookie('token', token, 3600)
            response.set_cookie('user_name', user_name, 3600)
            return response
        else:
            error_json = {'error_message' : 'Имя пользователя или пароль не корректны!'}
            return render(request, 'user_login.html', error_json)
    else:
        return render(request, 'user_login.html')

def login_success(request):
    #Получение имени пользователя из cookie.
    token = request.COOKIES.get('token','')
    user_name = request.COOKIES.get('user_name','')
    
    # Передача имени пользователя для отображения страницы.
    return render(request, 'user_login_success.html', {'user_name':user_name})

def user_register(request):
    # Очистка значения сеанса перед регистрацией.
    request.session['user_name'] = ''
    request.session['user_password'] = ''
    request.session['user_email'] = ''
    return render(request, 'user_register.html', {'user_name':'','user_password':'','user_email':''})

def do_register(request):
    request_method = request.method

    print('request_method = ' + request_method)

    if request_method == 'POST':
        user_name = request.POST.get('user_name', '')
        user_password = request.POST.get('user_password', '')
        user_email = request.POST.get('user_email', '')

        if len(user_name) > 0 and len(user_password) > 0 and len(user_email) > 0:
            # Перенаправление страницы на страницу register_success.
            response = HttpResponseRedirect('/user/register_success/')
            # Установка имени пользователя, пароля и почты.
            request.session['user_name'] = user_name
            request.session['user_password'] = user_password
            request.session['user_email'] = user_email
            return response
        else:
            error_json = {'error_message': 'User name, password and email can not be empty.'}
            return render(request, 'user_register.html', error_json)
    else:
        return render(request, 'user_register.html')


def register_success(request):
    # Получение значений имени пользователя, пароля и почты из сессии.
    user_name = request.session.get('user_name','')
    user_password = request.session.get('user_password', '')
    user_email = request.session.get('user_email', '')
    # pПередача имени пользователя, пароля и почты для отображения веб-страницы.
    return render(request, 'user_register_success.html', {'user_name':user_name,'user_password':user_password,'user_email':user_email})

django_riddles1234/django_riddles/riddles/templates/answer.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'C:\Users\Ilya\django_example\riddles\static\main.css' %}" />

<h1>{{ riddle.riddle_text }}</h1>

{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}

<form action="{% url 'riddles:answer' riddle.id %}" method="post">
    {% csrf_token %}
    {% for option in riddle.option_set.all %}
        <input type="radio" name="option" id="option{{ forloop.counter }}" value="{{ option.id }}" />
        <label for="option{{ forloop.counter }}">{{ option.text }}</label><br />
    {% endfor %}
    <input type="submit" value="Answer" />
</form>

django_riddles1234/django_riddles/riddles/templates/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />

<h1>Доступные загадки</h1>

{% if message %}
    <p><strong>{{ message }}</strong></p>
{% endif %}

{% if latest_riddles %}

    <ul>
        {% for riddle in latest_riddles %}
            <li>
                <a href="/riddles/{{ riddle.id }}/">
                    {{ riddle.riddle_text }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% else %}
    <p>No riddles are available right now.</p>
{% endif %}

django_riddles1234/django_riddles/user_register_login/templates/menu_bar.html
<a href="/" style="margin-right: 15px">Войти</a><a href="/user/register/">Зарегистрироваться</a><br/>

django_riddles1234/django_riddles/user_register_login/templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login Page</title>
</head>
<body>
{% include "./menu_bar.html" %}
<h3>Введите имя пользователя и пароль</h3>
<form method="post" action="/user/do_login/">
    {% if error_message %}
          <font color="red">{{ error_message }}</font><br/>
    {% endif %}
    Имя пользователя: <input name="user_name" type="text" placeholder="user_name"><br/>
    Пароль: <input name="user_password" type="password" placeholder="user_password"><br/>
    <br>
    <button type="submit">Подтвердить</button>
    <!-- this template tag will avoid 'CSRF verification failed. Request aborted' error. -->
    {% csrf_token %}
</form>
</body>
</html>

django_riddles1234/django_riddles/user_register_login/templates/user_login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login Success</title>
</head>
<body>
{% include "./menu_bar.html" %}
Приевет {{ user_name }}, ваши имя пользователя и пароль корректны.
<br><br><br>
<a href="/riddles">Начать игру в загадки.</a><br/>

</body>
</html>

django_riddles1234/django_riddles/user_register_login/templates/user_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Register Page</title>
</head>
<body>
{% include "./menu_bar.html" %}
<h3>Регистрация пользователя</h3>
<form method="post" action="/user/do_register/">
    {% if error_message %}
          <font color="red">{{ error_message }}</font><br/>
    {% endif %}
    Имя пользователя: <input name="user_name" type="text" placeholder="user_name" /><br/>
    Пароль: <input name="user_password" type="password" placeholder="user_password" /><br/>
    Email: <input name="user_email" type="text" placeholder="user_email" /><br/>
    <br>
    <button type="submit">Зарегистрировать</button>
    <!-- this template tag will avoid 'CSRF verification failed. Request aborted' error. -->
    {% csrf_token %}
</form>
</body>
</html>

django_riddles1234/django_riddles/user_register_login/templates/user_register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Успешная регистрация</title>
</head>
<body>
{% include "./menu_bar.html" %}
Привет {{ user_name }}, вы успешно зарегистрированы.<br/>
Имя пользователя : {{ user_name }}<br/>
Пароль : {{ user_password }}<br/>
Email : {{ user_email }}<br/>
</body>
</html>